version: '3.8'
services:
  blockchain-listener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monad-watcher-v1
    environment:
      - NODE_URL=${NODE_URL}
      - TRANSFER_THRESHOLD=${TRANSFER_THRESHOLD}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
